version: "3.2"

services:
  node:
    container_name: turnkey-private-blockchain-network
    image: cerebellumnetwork/turnkey-private-blockchain-network
    ports:
      - "9944:9944"
    command: bash -c "node-template --dev --ws-external"
  scenario_1:
    container_name: scenario_1
    image: test_scripts
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: node dist/index.js scenario_1
  scenario_2:
    container_name: scenario_2
    image: test_scripts
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: node dist/index.js scenario_2
  scenario_3:
    container_name: scenario_3
    image: test_scripts
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: node dist/index.js scenario_3
  scenario_4:
    container_name: scenario_4
    image: test_scripts
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: node dist/index.js scenario_4
  scenario_5:
    container_name: scenario_5
    image: test_scripts
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: node dist/index.js scenario_5
  scenario_6:
    container_name: scenario_6
    image: test_scripts
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: node dist/index.js scenario_6
